import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Box, IconButton, ButtonLink, Button, Flex } from "gestalt";
import { useState } from "react";
export const Navigation = ({ scheme, setScheme }) => {
    const [showMenu, setShowMenu] = useState(false);
    return (_jsxs(Box, { children: [_jsxs(Box, { role: "navigation", direction: "row", display: "flex", justifyContent: "end", paddingY: 3, children: [_jsx(IconButton, { accessibilityLabel: "Toggle color scheme", icon: scheme === "light" ? "moon" : "sun", onClick: () => setScheme(scheme === "light" ? "dark" : "light") }), _jsx(ButtonLink, { text: "GitHub", accessibilityLabel: "GitHub", size: "sm", color: "transparent", href: "https://github.com/YutaGoto/japanCityGacha", target: "blank", rel: "nofollow", iconStart: "visit" }), _jsx(ButtonLink, { text: "\u5E02\u753A\u6751\u4E00\u89A7", accessibilityLabel: "\u5E02\u753A\u6751\u4E00\u89A7", size: "sm", color: "transparent", href: "https://github.com/nojimage/local-gov-code-jp/blob/ba7a68463e2c68996e6a993640c21296a9cb0785/cities.json", target: "blank", rel: "nofollow", iconStart: "visit" }), _jsx(Button, { text: "\u97F3\u6E90", accessibilityLabel: "\u97F3\u6E90", size: "sm", iconStart: "menu", onClick: () => {
                            setShowMenu(!showMenu);
                        } })] }), showMenu && (_jsx(Box, { position: "absolute", top: true, right: true, marginTop: 16, marginEnd: 6, display: "flex", color: "default", alignItems: "center", justifyContent: "center", children: _jsxs(Flex, { alignItems: "end", direction: "column", gap: 2, children: [_jsx(ButtonLink, { text: "\u30C9\u30E9\u30E0", accessibilityLabel: "\u30C9\u30E9\u30E0\u30EB\u30FC\u30D7", size: "sm", color: "transparent", href: "https://pixabay.com/ja/sound-effects/noise-drum-loop-134bpm-245852/", target: "blank", rel: "nofollow", iconStart: "audio-bars" }), _jsx(ButtonLink, { text: "\u30B7\u30F3\u30D0\u30EB", accessibilityLabel: "\u30AF\u30E9\u30C3\u30B7\u30E5\u30B7\u30F3\u30D0\u30EB", size: "sm", color: "transparent", href: "https://pixabay.com/ja/sound-effects/tr707-crash-cymbal-241376/", target: "blank", rel: "nofollow", iconStart: "audio-bars" })] }) }))] }));
};
